server:
  port: 8080

spring:
  application:
    name: starnight
  # Redis
  redis:
    host: localhost
    port: 6379
    password: 123456
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starnight?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      StatViewServlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

# Mybatis 配置
mybatis:
  typeAliasesPackage: com.tracejp.starnight
  mapperLocations: classpath:mapper/*.xml

# star-night 配置
starnight:
  # 文件处理器
  file:
    url: localhost:9000
    access-key: 123456
    secret-key: 123456
    bucket-name: starnight
  # 自定义线程池
  thread:
    pool:
      core-pool-size: 50
      maximum-pool-size: 200
      keep-alive-time: 10
      blocking-queue-size: 1000
