server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starnight?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      StatViewServlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

# mybatis配置
mybatis:
  typeAliasesPackage: com.tracejp.starnight
  mapperLocations: classpath:mapper/*.xml
